-- MySQL Script generated by MySQL Workbench
-- Tue Jan 24 20:31:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`University`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`University` (
  `idUniversity` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Location` INT NULL DEFAULT 21,
  PRIMARY KEY (`idUniversity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dean`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dean` (
  `idDean` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Age` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDean`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mentor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mentor` (
  `idMentor` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Age` INT NOT NULL,
  `Gender` VARCHAR(45) NOT NULL,
  `idUniversity` INT NOT NULL,
  `idDean` INT NOT NULL,
  PRIMARY KEY (`idMentor`),
  INDEX `fk_Mentor_University1_idx` (`idUniversity` ASC) VISIBLE,
  INDEX `fk_Mentor_Dean1_idx` (`idDean` ASC) VISIBLE,
  CONSTRAINT `fk_Mentor_University1`
    FOREIGN KEY (`idUniversity`)
    REFERENCES `mydb`.`University` (`idUniversity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mentor_Dean1`
    FOREIGN KEY (`idDean`)
    REFERENCES `mydb`.`Dean` (`idDean`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `idCourse` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Course` INT NOT NULL,
  PRIMARY KEY (`idCourse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Faculty` (
  `idFaculty` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `idCourse` INT NOT NULL,
  `idDean` INT NOT NULL,
  PRIMARY KEY (`idFaculty`),
  INDEX `fk_Faculty_Course1_idx` (`idCourse` ASC) VISIBLE,
  INDEX `fk_Faculty_Dean1_idx` (`idDean` ASC) VISIBLE,
  CONSTRAINT `fk_Faculty_Course1`
    FOREIGN KEY (`idCourse`)
    REFERENCES `mydb`.`Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Faculty_Dean1`
    FOREIGN KEY (`idDean`)
    REFERENCES `mydb`.`Dean` (`idDean`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `idStundent` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Age` INT NOT NULL,
  `Gender` VARCHAR(45) NOT NULL,
  `idUniversity` INT NOT NULL,
  `Faculty_idFaculty` INT NOT NULL,
  PRIMARY KEY (`idStundent`),
  INDEX `fk_Student_University_idx` (`idUniversity` ASC) VISIBLE,
  INDEX `fk_Student_Faculty1_idx` (`Faculty_idFaculty` ASC) VISIBLE,
  CONSTRAINT `fk_Student_University`
    FOREIGN KEY (`idUniversity`)
    REFERENCES `mydb`.`University` (`idUniversity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_Faculty1`
    FOREIGN KEY (`Faculty_idFaculty`)
    REFERENCES `mydb`.`Faculty` (`idFaculty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Auditory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Auditory` (
  `idAuditory` INT NOT NULL,
  `Capacity` INT NULL,
  `idUniversity` INT NOT NULL,
  PRIMARY KEY (`idAuditory`),
  INDEX `fk_Auditory_University1_idx` (`idUniversity` ASC) VISIBLE,
  CONSTRAINT `fk_Auditory_University1`
    FOREIGN KEY (`idUniversity`)
    REFERENCES `mydb`.`University` (`idUniversity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `mydb`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Staff` (
  `idStaff` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Age` INT NOT NULL,
  `idUniversity` INT NOT NULL,
  PRIMARY KEY (`idStaff`),
  INDEX `fk_Staff_University1_idx` (`idUniversity` ASC) VISIBLE,
  CONSTRAINT `fk_Staff_University1`
    FOREIGN KEY (`idUniversity`)
    REFERENCES `mydb`.`University` (`idUniversity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student_has_Mentor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student_has_Mentor` (
  `idStundent` INT NOT NULL,
  `idMentor` INT NOT NULL,
  PRIMARY KEY (`idStundent`, `idMentor`),
  INDEX `fk_Student_has_Mentor_Mentor1_idx` (`idMentor` ASC) VISIBLE,
  INDEX `fk_Student_has_Mentor_Student1_idx` (`idStundent` ASC) VISIBLE,
  CONSTRAINT `fk_Student_has_Mentor_Student1`
    FOREIGN KEY (`idStundent`)
    REFERENCES `mydb`.`Student` (`idStundent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Mentor_Mentor1`
    FOREIGN KEY (`idMentor`)
    REFERENCES `mydb`.`Mentor` (`idMentor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Oweing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Oweing` (
  `idOweing` INT NOT NULL,
  `Amount_of_Oweing` INT NULL,
  `idStundent` INT NOT NULL,
  PRIMARY KEY (`idOweing`),
  INDEX `fk_Oweing_Student1_idx` (`idStundent` ASC) VISIBLE,
  CONSTRAINT `fk_Oweing_Student1`
    FOREIGN KEY (`idStundent`)
    REFERENCES `mydb`.`Student` (`idStundent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
